using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using OpenUtau.Core.Theming;
using Xunit;

namespace OpenUtau.Test.Tools {
    /// <summary>
    /// **一次性生成器**：把主程序的 MD3 调色板算法跑一次，产出安装器**写死**用的调色板常量。
    ///
    /// 背景：安装器要求「不用动态色彩 / 不建色池 / 亮暗两套编码颜色写死，颜色梯度从主程序拿」
    /// （用户 2026-10 原话）⇒ 正确做法不是手挑色值，而是**用主程序同一个算法**
    /// （<see cref="Md3SchemeColors.Create"/>）以固定 seed 生成一次，把结果**固化成 C# 常量**。
    ///
    /// 触发（默认 no-op，保证全量测试一直绿）：
    /// <code>
    /// $env:OPENUTAU_GEN_MD3_PALETTE='1'
    /// $env:OPENUTAU_GEN_MD3_SEED='0xFF0B57D0'     # 可选，默认 Material Blue
    /// $env:OPENUTAU_GEN_MD3_OUT='installer/UTvTU.Installer/InstallerPalette.cs'   # 可选
    /// dotnet test OpenUtau.Test\OpenUtau.Test.csproj --filter FullyQualifiedName~Md3PaletteDump
    /// </code>
    /// </summary>
    public class Md3PaletteDump {
        private readonly ITestOutputHelper output;
        public Md3PaletteDump(ITestOutputHelper output) => this.output = output;

        /// <summary>安装器实际用到的**最小角色集**（其余 49 个角色不生成，保持文件小）。</summary>
        private static readonly Md3Role[] Wanted = {
            Md3Role.Background, Md3Role.OnBackground,
            Md3Role.Surface, Md3Role.SurfaceContainerLow, Md3Role.SurfaceContainer,
            Md3Role.SurfaceContainerHigh, Md3Role.SurfaceContainerHighest,
            Md3Role.OnSurface, Md3Role.SurfaceVariant, Md3Role.OnSurfaceVariant,
            Md3Role.Outline, Md3Role.OutlineVariant,
            Md3Role.Primary, Md3Role.OnPrimary, Md3Role.PrimaryContainer, Md3Role.OnPrimaryContainer,
            Md3Role.Secondary, Md3Role.OnSecondary, Md3Role.SecondaryContainer, Md3Role.OnSecondaryContainer,
            Md3Role.Error, Md3Role.OnError, Md3Role.ErrorContainer, Md3Role.OnErrorContainer,
            Md3Role.InverseSurface, Md3Role.InverseOnSurface, Md3Role.Scrim, Md3Role.Shadow,
        };

        private static uint ParseSeed(string? raw, uint fallback) {
            if (string.IsNullOrWhiteSpace(raw)) {
                return fallback;
            }
            string s = raw.Trim();
            if (s.StartsWith("0x", StringComparison.OrdinalIgnoreCase)) {
                return Convert.ToUInt32(s.Substring(2), 16);
            }
            return uint.TryParse(s, out uint v) ? v : fallback;
        }

        private static string RepoRoot() {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "OpenUtau.sln"))) {
                dir = dir.Parent;
            }
            return dir?.FullName ?? AppContext.BaseDirectory;
        }

        private static string Emit(string name, Md3SchemeColors colors) {
            var sb = new StringBuilder();
            sb.AppendLine($"        public static readonly IReadOnlyDictionary<InstRole, Color> {name} =");
            sb.AppendLine("            new Dictionary<InstRole, Color> {");
            foreach (Md3Role role in Wanted) {
                uint argb = colors.Get(role);
                sb.AppendLine($"                [InstRole.{role}] = Color.FromArgb(0x{(argb >> 24) & 0xFF:X2}, " +
                              $"0x{(argb >> 16) & 0xFF:X2}, 0x{(argb >> 8) & 0xFF:X2}, 0x{argb & 0xFF:X2}),");
            }
            sb.AppendLine("            };");
            return sb.ToString();
        }

        [Fact]
        public void DumpInstallerPalette() {
            if (Environment.GetEnvironmentVariable("OPENUTAU_GEN_MD3_PALETTE") != "1") {
                return;   // 默认 no-op
            }

            uint seed = ParseSeed(Environment.GetEnvironmentVariable("OPENUTAU_GEN_MD3_SEED"), 0xFF0B57D0);
            var variant = Md3SchemeVariant.TonalSpot;   // 与 App.axaml.cs 的默认一致
            Md3SchemeColors light = Md3SchemeColors.Create(seed, variant, isDark: false);
            Md3SchemeColors dark = Md3SchemeColors.Create(seed, variant, isDark: true);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   由 OpenUtau.Test/Tools/Md3PaletteDump.cs 生成 —— **勿手改**。");
            sb.AppendLine($"//   来源：主程序同一套 MD3 算法 Md3SchemeColors.Create(seed=0x{seed:X8}, {variant}, isDark)，");
            sb.AppendLine("//   角色集为安装器实际用到的最小集（其余角色不生成）。");
            sb.AppendLine("//   重生成：设 OPENUTAU_GEN_MD3_PALETTE=1 后跑 Md3PaletteDump.DumpInstallerPalette。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Avalonia.Media;");
            sb.AppendLine();
            sb.AppendLine("namespace UTvTU.Installer {");
            sb.AppendLine("    /// <summary>安装器用到的 MD3 角色（最小集）。与主程序 Md3Role 同名，但**本地定义**");
            sb.AppendLine("    /// ⇒ 安装器零依赖主程序工程（构建快、发布小）。</summary>");
            sb.AppendLine("    public enum InstRole {");
            foreach (Md3Role role in Wanted) {
                sb.AppendLine($"        {role},");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>安装器调色板（写死）：亮/暗两套，来自主程序算法的一次性固化。</summary>");
            sb.AppendLine("    public static class InstallerPalette {");
            sb.Append($"        public const uint Seed = 0x{seed:X8};");
            sb.AppendLine();
            sb.AppendLine();
            sb.Append(Emit("Light", light));
            sb.AppendLine();
            sb.Append(Emit("Dark", dark));
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string rel = Environment.GetEnvironmentVariable("OPENUTAU_GEN_MD3_OUT") is { Length: > 0 } custom
                ? custom
                : Path.Combine("installer", "UTvTU.Installer", "InstallerPalette.cs");
            string outPath = Path.IsPathRooted(rel) ? rel : Path.Combine(RepoRoot(), rel);
            Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
            File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));

            output.WriteLine($"seed=0x{seed:X8} roles={Wanted.Length} -> {outPath}");
            output.WriteLine($"light Primary=#{light.Get(Md3Role.Primary):X8} Surface=#{light.Get(Md3Role.Surface):X8}");
            output.WriteLine($"dark  Primary=#{dark.Get(Md3Role.Primary):X8} Surface=#{dark.Get(Md3Role.Surface):X8}");
        }
    }
}
