// <auto-generated>
//   由 OpenUtau.Test/Tools/Md3PaletteDump.cs 生成 —— **勿手改**。
//   来源：主程序同一套 MD3 算法 Md3SchemeColors.Create(seed=0xFF0B57D0, TonalSpot, isDark)，
//   角色集为安装器实际用到的最小集（其余角色不生成）。
//   重生成：设 OPENUTAU_GEN_MD3_PALETTE=1 后跑 Md3PaletteDump.DumpInstallerPalette。
// </auto-generated>

using System.Collections.Generic;
using Avalonia.Media;

namespace UTvTU.Installer {
    /// <summary>安装器用到的 MD3 角色（最小集）。与主程序 Md3Role 同名，但**本地定义**
    /// ⇒ 安装器零依赖主程序工程（构建快、发布小）。</summary>
    public enum InstRole {
        Background,
        OnBackground,
        Surface,
        SurfaceContainerLow,
        SurfaceContainer,
        SurfaceContainerHigh,
        SurfaceContainerHighest,
        OnSurface,
        SurfaceVariant,
        OnSurfaceVariant,
        Outline,
        OutlineVariant,
        Primary,
        OnPrimary,
        PrimaryContainer,
        OnPrimaryContainer,
        Secondary,
        OnSecondary,
        SecondaryContainer,
        OnSecondaryContainer,
        Error,
        OnError,
        ErrorContainer,
        OnErrorContainer,
        InverseSurface,
        InverseOnSurface,
        Scrim,
        Shadow,
    }

    /// <summary>安装器调色板（写死）：亮/暗两套，来自主程序算法的一次性固化。</summary>
    public static class InstallerPalette {
        public const uint Seed = 0xFF0B57D0;

        public static readonly IReadOnlyDictionary<InstRole, Color> Light =
            new Dictionary<InstRole, Color> {
                [InstRole.Background] = Color.FromArgb(0xFF, 0xFA, 0xF8, 0xFF),
                [InstRole.OnBackground] = Color.FromArgb(0xFF, 0x1A, 0x1B, 0x21),
                [InstRole.Surface] = Color.FromArgb(0xFF, 0xFA, 0xF8, 0xFF),
                [InstRole.SurfaceContainerLow] = Color.FromArgb(0xFF, 0xF4, 0xF3, 0xFA),
                [InstRole.SurfaceContainer] = Color.FromArgb(0xFF, 0xEE, 0xED, 0xF4),
                [InstRole.SurfaceContainerHigh] = Color.FromArgb(0xFF, 0xE8, 0xE7, 0xEF),
                [InstRole.SurfaceContainerHighest] = Color.FromArgb(0xFF, 0xE2, 0xE2, 0xE9),
                [InstRole.OnSurface] = Color.FromArgb(0xFF, 0x1A, 0x1B, 0x21),
                [InstRole.SurfaceVariant] = Color.FromArgb(0xFF, 0xE1, 0xE2, 0xEC),
                [InstRole.OnSurfaceVariant] = Color.FromArgb(0xFF, 0x45, 0x46, 0x4F),
                [InstRole.Outline] = Color.FromArgb(0xFF, 0x75, 0x77, 0x80),
                [InstRole.OutlineVariant] = Color.FromArgb(0xFF, 0xC5, 0xC6, 0xD0),
                [InstRole.Primary] = Color.FromArgb(0xFF, 0x49, 0x5D, 0x92),
                [InstRole.OnPrimary] = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF),
                [InstRole.PrimaryContainer] = Color.FromArgb(0xFF, 0xDA, 0xE2, 0xFF),
                [InstRole.OnPrimaryContainer] = Color.FromArgb(0xFF, 0x30, 0x45, 0x78),
                [InstRole.Secondary] = Color.FromArgb(0xFF, 0x58, 0x5E, 0x71),
                [InstRole.OnSecondary] = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF),
                [InstRole.SecondaryContainer] = Color.FromArgb(0xFF, 0xDC, 0xE2, 0xF9),
                [InstRole.OnSecondaryContainer] = Color.FromArgb(0xFF, 0x40, 0x46, 0x59),
                [InstRole.Error] = Color.FromArgb(0xFF, 0xBA, 0x1A, 0x1A),
                [InstRole.OnError] = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF),
                [InstRole.ErrorContainer] = Color.FromArgb(0xFF, 0xFF, 0xDA, 0xD6),
                [InstRole.OnErrorContainer] = Color.FromArgb(0xFF, 0x93, 0x00, 0x0A),
                [InstRole.InverseSurface] = Color.FromArgb(0xFF, 0x2F, 0x30, 0x36),
                [InstRole.InverseOnSurface] = Color.FromArgb(0xFF, 0xF1, 0xF0, 0xF7),
                [InstRole.Scrim] = Color.FromArgb(0xFF, 0x00, 0x00, 0x00),
                [InstRole.Shadow] = Color.FromArgb(0xFF, 0x00, 0x00, 0x00),
            };

        public static readonly IReadOnlyDictionary<InstRole, Color> Dark =
            new Dictionary<InstRole, Color> {
                [InstRole.Background] = Color.FromArgb(0xFF, 0x12, 0x13, 0x18),
                [InstRole.OnBackground] = Color.FromArgb(0xFF, 0xE2, 0xE2, 0xE9),
                [InstRole.Surface] = Color.FromArgb(0xFF, 0x12, 0x13, 0x18),
                [InstRole.SurfaceContainerLow] = Color.FromArgb(0xFF, 0x1A, 0x1B, 0x21),
                [InstRole.SurfaceContainer] = Color.FromArgb(0xFF, 0x1E, 0x1F, 0x25),
                [InstRole.SurfaceContainerHigh] = Color.FromArgb(0xFF, 0x28, 0x2A, 0x2F),
                [InstRole.SurfaceContainerHighest] = Color.FromArgb(0xFF, 0x33, 0x34, 0x3A),
                [InstRole.OnSurface] = Color.FromArgb(0xFF, 0xE2, 0xE2, 0xE9),
                [InstRole.SurfaceVariant] = Color.FromArgb(0xFF, 0x45, 0x46, 0x4F),
                [InstRole.OnSurfaceVariant] = Color.FromArgb(0xFF, 0xC5, 0xC6, 0xD0),
                [InstRole.Outline] = Color.FromArgb(0xFF, 0x8F, 0x90, 0x9A),
                [InstRole.OutlineVariant] = Color.FromArgb(0xFF, 0x45, 0x46, 0x4F),
                [InstRole.Primary] = Color.FromArgb(0xFF, 0xB2, 0xC5, 0xFF),
                [InstRole.OnPrimary] = Color.FromArgb(0xFF, 0x17, 0x2E, 0x60),
                [InstRole.PrimaryContainer] = Color.FromArgb(0xFF, 0x30, 0x45, 0x78),
                [InstRole.OnPrimaryContainer] = Color.FromArgb(0xFF, 0xDA, 0xE2, 0xFF),
                [InstRole.Secondary] = Color.FromArgb(0xFF, 0xC0, 0xC6, 0xDD),
                [InstRole.OnSecondary] = Color.FromArgb(0xFF, 0x2A, 0x30, 0x42),
                [InstRole.SecondaryContainer] = Color.FromArgb(0xFF, 0x40, 0x46, 0x59),
                [InstRole.OnSecondaryContainer] = Color.FromArgb(0xFF, 0xDC, 0xE2, 0xF9),
                [InstRole.Error] = Color.FromArgb(0xFF, 0xFF, 0xB4, 0xAB),
                [InstRole.OnError] = Color.FromArgb(0xFF, 0x69, 0x00, 0x05),
                [InstRole.ErrorContainer] = Color.FromArgb(0xFF, 0x93, 0x00, 0x0A),
                [InstRole.OnErrorContainer] = Color.FromArgb(0xFF, 0xFF, 0xDA, 0xD6),
                [InstRole.InverseSurface] = Color.FromArgb(0xFF, 0xE2, 0xE2, 0xE9),
                [InstRole.InverseOnSurface] = Color.FromArgb(0xFF, 0x2F, 0x30, 0x36),
                [InstRole.Scrim] = Color.FromArgb(0xFF, 0x00, 0x00, 0x00),
                [InstRole.Shadow] = Color.FromArgb(0xFF, 0x00, 0x00, 0x00),
            };
    }
}
