// 代码生成 v2：角色规格（含"tone 随对比度变化"的曲线）
// 输出 OpenUtau.Core/Theming/Md3RoleTable.g.cs 与 Md3Role.g.cs
const fs = require('fs');
const path = require('path');
const m = require('@material/material-color-utilities');

const OUT = process.argv[2] || path.join(__dirname, '..', '..', 'OpenUtau.Core', 'Theming', 'Md3RoleTable.g.cs');

const schemes = {
    TonalSpot: m.SchemeTonalSpot, Vibrant: m.SchemeVibrant, Expressive: m.SchemeExpressive,
    Monochrome: m.SchemeMonochrome, Neutral: m.SchemeNeutral, Rainbow: m.SchemeRainbow, FruitSalad: m.SchemeFruitSalad,
};
const NORMAL = ['TonalSpot', 'Vibrant', 'Expressive', 'Neutral', 'Rainbow', 'FruitSalad'];
const PAL_KEYS = ['primaryPalette', 'secondaryPalette', 'tertiaryPalette', 'neutralPalette', 'neutralVariantPalette', 'errorPalette'];
const SKIP = ['length', 'name', 'prototype', 'highestSurface', 'contentAccentToneDelta'];
const roleNames = Object.getOwnPropertyNames(m.MaterialDynamicColors)
    .filter(k => !SKIP.includes(k))
    .filter(k => m.MaterialDynamicColors[k] instanceof m.DynamicColor)
    .filter(k => !k.endsWith('PaletteKeyColor'));

const pascal = s => s.charAt(0).toUpperCase() + s.slice(1);
const byName = new Map(roleNames.map(r => [m.MaterialDynamicColors[r].name, r]));
const roleRef = dc => {
    if (!dc) return null;
    const r = byName.get(dc.name);
    if (!r) throw new Error('引用了集合外的角色: ' + dc.name);
    return r;
};

const CONTROL = [-1, 0, 0.5, 1];             // 曲线的四个控制点
const CHECK = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1];   // 校验点
const seed = 0xff6750a4;
const anomalies = [];

// 与参考实现 ContrastCurve.get 同语义
function curveGet(c, cl) {
    if (cl <= -1.0) return c[0];
    if (cl < 0.0) return (1 - (cl + 1) / 1) * c[0] + ((cl + 1) / 1) * c[1];
    if (cl < 0.5) return (1 - cl / 0.5) * c[1] + (cl / 0.5) * c[2];
    if (cl < 1.0) return (1 - (cl - 0.5) / 0.5) * c[2] + ((cl - 0.5) / 0.5) * c[3];
    return c[3];
}

function toneCurveOf(role, variant, dark) {
    const dc = m.MaterialDynamicColors[role];
    const c = CONTROL.map(cl => {
        const s = new schemes[variant](m.Hct.fromInt(seed), dark, cl);
        const t = dc.tone(s);
        return Number.isInteger(t) ? t : +t.toFixed(6);
    });
    // 校验中间点能否由曲线复现
    for (const cl of CHECK) {
        const s = new schemes[variant](m.Hct.fromInt(seed), dark, cl);
        const actual = dc.tone(s);
        const predicted = curveGet(c, cl);
        if (Math.abs(actual - predicted) > 1e-6) {
            anomalies.push(`${role}/${variant}/${dark ? 'dark' : 'light'}: tone 非分段线性 cl=${cl} 实际=${actual} 曲线预测=${predicted}`);
        }
    }
    return c;
}

const specs = {};
for (const r of roleNames) {
    const dc = m.MaterialDynamicColors[r];
    const sLight = new schemes.TonalSpot(m.Hct.fromInt(seed), false, 0);
    const sDark = new schemes.TonalSpot(m.Hct.fromInt(seed), true, 0);
    const palette = PAL_KEYS.find(k => sLight[k] === dc.palette(sLight));
    if (!palette) throw new Error('无法判定色板: ' + r);

    // normal 六变体必须给出同一条曲线
    const normalLight = NORMAL.map(v => JSON.stringify(toneCurveOf(r, v, false)));
    const normalDark = NORMAL.map(v => JSON.stringify(toneCurveOf(r, v, true)));
    if (new Set(normalLight).size !== 1) anomalies.push(`${r}: normal light tone 曲线在各变体间不一致 -> ${[...new Set(normalLight)].join(' | ')}`);
    if (new Set(normalDark).size !== 1) anomalies.push(`${r}: normal dark tone 曲线在各变体间不一致 -> ${[...new Set(normalDark)].join(' | ')}`);

    const cc = dc.contrastCurve;
    const tdp = dc.toneDeltaPair ? dc.toneDeltaPair(sLight) : null;

    specs[r] = {
        role: pascal(r), palette: pascal(palette.replace('Palette', '')),
        isBackground: !!dc.isBackground,
        bgLight: dc.background ? pascal(roleRef(dc.background(sLight))) : null,
        bgDark: dc.background ? pascal(roleRef(dc.background(sDark))) : null,
        sbLight: dc.secondBackground ? pascal(roleRef(dc.secondBackground(sLight))) : null,
        sbDark: dc.secondBackground ? pascal(roleRef(dc.secondBackground(sDark))) : null,
        cc: cc ? [cc.low, cc.normal, cc.medium, cc.high] : null,
        tdp: tdp ? [pascal(byName.get(tdp.roleA.name)), pascal(byName.get(tdp.roleB.name)), tdp.delta, tdp.polarity, tdp.stayTogether] : null,
        toneLight: JSON.parse(normalLight[0]),
        toneDark: JSON.parse(normalDark[0]),
        monoLight: toneCurveOf(r, 'Monochrome', false),
        monoDark: toneCurveOf(r, 'Monochrome', true),
    };
}

const ccurve = a => `new Md3ContrastCurve(${a[0]}, ${a[1]}, ${a[2]}, ${a[3]})`;
const L = [];
L.push('// <auto-generated>');
L.push('//   本文件由 tools/md3-codegen/codegen.js 从 Google material-color-utilities@0.3.0 内省生成，请勿手改。');
L.push('//   来源：MaterialDynamicColors 的 49 个 DynamicColor 角色（已排除 *PaletteKeyColor 诊断角色）。');
L.push('//   tone 一律表示成对比度曲线（常量即四点相同）——参考实现中 surfaceDim 等角色的 tone 本身随对比度变化。');
L.push('//   重新生成：node codegen.js（需 node_modules/@material/material-color-utilities@0.3.0）。');
L.push('// </auto-generated>');
L.push('');
L.push('namespace OpenUtau.Core.Theming {');
L.push('    internal static class Md3RoleTable {');
L.push('        internal static readonly Md3RoleSpec[] Roles = new Md3RoleSpec[] {');
for (const r of roleNames) {
    const s = specs[r];
    const tdp = s.tdp
        ? `new Md3ToneDeltaPair(Md3Role.${s.tdp[0]}, Md3Role.${s.tdp[1]}, ${s.tdp[2]}, Md3TonePolarity.${s.tdp[3] === 'nearer' ? 'Nearer' : s.tdp[3] === 'lighter' ? 'Lighter' : 'Darker'}, ${s.tdp[4] ? 'true' : 'false'})`
        : 'null';
    L.push(`            new Md3RoleSpec(Md3Role.${s.role}, Md3PaletteKind.${s.palette}, ${s.isBackground ? 'true' : 'false'},`);
    L.push(`                ${s.bgLight ? 'Md3Role.' + s.bgLight : 'null'}, ${s.bgDark ? 'Md3Role.' + s.bgDark : 'null'},`);
    L.push(`                ${s.sbLight ? 'Md3Role.' + s.sbLight : 'null'}, ${s.sbDark ? 'Md3Role.' + s.sbDark : 'null'},`);
    L.push(`                ${s.cc ? ccurve(s.cc) : 'null'}, ${tdp},`);
    L.push(`                ${ccurve(s.toneLight)}, ${ccurve(s.toneDark)},`);
    L.push(`                ${ccurve(s.monoLight)}, ${ccurve(s.monoDark)}),`);
}
L.push('        };');
L.push('    }');
L.push('}');
L.push('');
fs.writeFileSync(OUT, L.join('\n'));

const enumPath = path.join(path.dirname(OUT), 'Md3Role.g.cs');
const E = ['// <auto-generated>',
    '//   本文件由 tools/md3-codegen/codegen.js 从 Google material-color-utilities@0.3.0 内省生成，请勿手改。',
    '// </auto-generated>', '', 'namespace OpenUtau.Core.Theming {',
    '    /// <summary>Material Design 3 色角色（MD3 color roles）。</summary>',
    '    public enum Md3Role {'];
for (const r of roleNames) E.push(`        ${pascal(r)},`);
E.push('    }', '}', '');
fs.writeFileSync(enumPath, E.join('\n'));

console.log(`已生成 ${OUT}（${roleNames.length} 角色）与 ${enumPath}`);
const curved = roleNames.filter(r => JSON.stringify(specs[r].toneLight) !== JSON.stringify([specs[r].toneLight[0], specs[r].toneLight[0], specs[r].toneLight[0], specs[r].toneLight[0]])
    || JSON.stringify(specs[r].toneDark) !== JSON.stringify([specs[r].toneDark[0], specs[r].toneDark[0], specs[r].toneDark[0], specs[r].toneDark[0]]));
console.log('tone 随对比度变化的角色：', curved.join(', ') || '（无）');
if (anomalies.length) { console.log('⚠ 异常：'); console.log(anomalies.join('\n')); } else { console.log('校验通过：tone 曲线在 9 个对比度采样点上完全复现，且 normal 六变体一致'); }
